INSERT INTO ORGANIZATION (NAME)
VALUES ('SSI');
INSERT INTO DEPARTMENT (NAME, ORGANIZATION_ID)
VALUES ('IT DEPARTMENT', 1);
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, POSITION, SALARY, AGE, DEPARTMENT_ID, ORGANIZATION_ID)
VALUES
('BILAL', 'DJAGO', 'FULLSTACK DEVELOPER', 1, 1, 1, 1),
('RAOUF', 'BISOU', 'FULLSTACK DEVELOPER', 1, 1, 1, 1);
